In [1]:
import numpy


In [2]:
empty= np.empty((2,2))
empty

NameError: name 'np' is not defined

In [3]:
import numpy as np


In [4]:
empty= np.empty((2,2))
empty

array([[4.93218412e-312, 7.49054040e+247],
       [2.42766851e-154, 5.03430672e+180]])

In [8]:
list1= [[1,2,0],[3,4,4,30],[5,6,7]]
a=np.array(list1)
a


array([list([1, 2, 0]), list([3, 4, 4, 30]), list([5, 6, 7])],
      dtype=object)

In [10]:
a[2,2]

IndexError: too many indices for array

In [7]:
a[0,2]

IndexError: index 2 is out of bounds for axis 1 with size 2

In [17]:
a=[[[1,3],[2,4],[5,6]],[[1,3],[2,45],[5,6]]]
a=np.array(a)

a[1,1,1]


In [29]:
#odd numbers
# even numb
np.arange(1,100)

array([ 1,  8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99])

In [31]:
12*np.arange(1,13)

array([ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144])

In [32]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [34]:
a=[[[1,3],[2,4],[5,6]],[[1,3],[2,45],[5,6]]]
a=np.array(a)


In [35]:
a

array([[[ 1,  3],
        [ 2,  4],
        [ 5,  6]],

       [[ 1,  3],
        [ 2, 45],
        [ 5,  6]]])

In [37]:
a[:,0:3:2,:]

array([[[1, 3],
        [5, 6]],

       [[1, 3],
        [5, 6]]])

In [39]:
b=a[0]
b


array([[1, 3],
       [2, 4],
       [5, 6]])

In [159]:
b[0:]

array([[1, 3],
       [2, 4],
       [5, 6]])

In [41]:
b[:]

array([[1, 3],
       [2, 4],
       [5, 6]])

## b[2:2]

In [43]:
b[1:2]

array([[2, 4]])

In [44]:
b[1:3]

array([[2, 4],
       [5, 6]])

In [45]:
b[1,:]

array([2, 4])

In [46]:
b[2,1:3]

array([6])

In [47]:
b


array([[1, 3],
       [2, 4],
       [5, 6]])

In [48]:
b[:,1]

array([3, 4, 6])

In [49]:
b[1,:]

array([2, 4])

In [167]:
c=np.zeros((5,5))
c[1:4,1:4]=1
c

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### c[0:2]=1
c


In [69]:
c[4:4]=1
c

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [70]:
c

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [71]:
c=np.zeros((5,5))
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [78]:
c[0,:]=1
c[4,:]=1
c[:,0]=1
c[:,4]=1
c[:,1]=0
c[]

array([[1., 0., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 1., 1., 1.]])

In [83]:
c[0,:]=1
c[4,:]=1
c[:,0]=1
c[:,4]=1

c


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [94]:
d=np.ones((5,5))
d[1:4,1:4]=0
d

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [97]:
d[1:4]

array([[1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.]])

In [ ]:
#chacker bOARD
'''
10101010
01010101
10101010
01010101
10101010
01010101
10101010
01010101



In [101]:
e=np.zeros((8,8))
e

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [125]:
e[::2,::2]=1
e[1::2,1::2]=0
e

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [153]:
f=np.zeros((10,10))
f
f[::2]=1
f

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [151]:
e=np.zeros((10,10))
e
e[1::2]=1
e

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [168]:
e.dtype


dtype('float64')

In [174]:
e=e.stype('int64')
e.dtype

AttributeError: 'numpy.ndarray' object has no attribute 'stype'

In [175]:
b


array([[1, 3],
       [2, 4],
       [5, 6]])

In [177]:
b[b<3]

array([1, 2])

In [179]:
names=np.array(['Arhan','Jawes','Akbar','waheed'])
ages = np.array([22,25,27,69])



In [180]:
    names[ages>50]

array(['waheed'], dtype='<U6')

In [181]:
ages[ages>50]

array([69])